### ISSUE TITLE
Neukladá/nevypĺňa adresu prechodného pobytu

### ISSUE THREAD

**Issue by andrewshadura** [pomali/nczi-vakcinacia-extension#1]
Pri uložení formulára mal som vyplnenú druhú adresu, vyplnenie na ňu zabudlo:
![Screenshot from 2021-03-09 08-41-36](https://user-images.githubusercontent.com/309253/110435493-5f38ee80-80b3-11eb-982b-c108dfe20059.png)

**Comment by pomali** [comment]
Je to sposobene tym, ze sa form dynamicky meni. Treba vymysliet ako to obabrat, mozno dva prechody a requestAnimationFrame medzi nimi.

**Comment by stanop** [comment]
ano pri obnove udajov treba najprv zaskrtnut checkboxy pockat kym sa vykonaju veci a potom fillovat zvysne data

**Comment by pomali** [comment]
funguje aj dva krat stlacit vyplnenie 😋
