### ISSUE TITLE
Firefox 86.0.1

### ISSUE THREAD

**Issue by Dareiko** [pomali/nczi-vakcinacia-extension#10]
Plugin 0.3.3. vie ulozit len jednu osobu, vykliklanie formularu nanovo prepise existujucu osobu hoci ma ine meno a r.c.

**Comment by pomali** [comment]
Urobim fix. 

Teraz ked existuje "cakaren" pouzivate extension na vyplnanie testovacich formularov?

**Comment by Dareiko** [comment]
Zatial to pouzivam lenna formular na ag testovanie.

Dňa ut 23. 3. 2021, 0:29 pomali ***@***.***> napísal(a):
